networks:
  webnet:
    driver: bridge

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config/searxng/settings.yml:/etc/searxng/settings.yml:ro
    networks:
      - webnet

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    depends_on:
      - searxng
    ports:
      - "3000:8080"
    volumes:
      - ./volumes/openwebui:/app/backend/data
    networks:
      - webnet
